version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql_container
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: devevolve
      MYSQL_ROOT_PASSWORD: DevEvolve321!
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_container
    restart: unless-stopped
    ports:
      - "8081:80" # Access phpMyAdmin at http://localhost:8081
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ""
    depends_on:
      - db

volumes:
  db_data:
